feat: document types improvements
denodrivers/deno_mongo pull request #239
Opened 2021-08-24 17:47 UTC by ablause

This PR is not finished, I want to add types for aggregation. 
Someone would help me to check if everything works?

Fixes: #237 #183

2021-08-24 18:13 UTC, erfanium commented
Great job!
I'll check when it's green

2021-08-25 10:10 UTC, ablause commented
I have some concerns about my projects with this PR, I'll fix it right away..

2021-08-31 02:09 UTC, manyuanrong commented
@ablause Nice work, do you still need to make other changes?

2021-08-31 09:56 UTC, ablause commented
@manyuanrong Yes, I'm finishing the last changes today

2021-08-31 14:52 UTC, erfanium requested changes

2021-08-31 14:52 UTC, erfanium commented on src/collection/collection.ts
> +        (doc as any)._id = new Bson.ObjectID();
```suggestion
        (doc as any)._id = new Bson.ObjectId();
```

To fix conflict

2021-09-01 15:35 UTC, ablause commented
I tried to fill in as much as possible, I hope I didn't make too many mistakes.  The operators value for the aggregations are missing, if one day I have the courage to do it, I'll do a pull-request especially for this one

2021-09-06 07:57 UTC, merged